/* global React */
/* GENERATED by scripts/sync.js — DO NOT EDIT BY HAND. */
/* Hand-curated content (FAQ, QUOTES, STATS, FEATURES, FILTERS) lives in data-static.jsx */
/* Generated: 2026-05-30T10:44:05.383Z */

const EPISODES = [
  {
    n: "27",
    title: "$40M FinTech Founder on Raising Millions Before He Had a Business Idea | Shakeel Lala, Marloo",
    guest: "Shakeel Lala",
    company: "Marloo",
    role: "Co-founder, Marloo",
    tags: [],
    primaryTag: "Founders",
    desc: "Shakeel quit his job, convinced Australia's largest VC to back him with no business idea, ran 800 conversations with financial advisors over 9 months, then vibe-coded a demo the week before Australia's biggest financial advice conference. People tried to buy it on the spot. Marloo has since raised $10M and is live across 6 countries.",
    url: "episodes/27-shakeel-lala/",
    dur: "35 min",
    date: "Aug 5, 2026",
    featured: true
  },
  {
    n: "25",
    title: "This Stanford Dropout Wants to Help You Fall in Love | Celeste Amadon, Known",
    guest: "Celeste Amadon",
    company: "Known",
    role: "Co-founder & CEO, Known",
    tags: [],
    primaryTag: "Founders",
    desc: "Celeste was 21 when she walked into Forerunner Ventures. She raised her pre-seed in 8 days, her seed in 4 days, and fielded 12+ term sheets. Known has set up 1,500 curated dates in beta and hundreds of couples are now in relationships. Her thesis: today's apps are perversely incentivised to keep you single and paying.",
    url: "episodes/25-celeste-amadon/",
    dur: "29 min",
    date: "Sep 4, 2026",
    featured: true
  },
  {
    n: "24",
    title: "How He Turned 3 YC Rejections into a $25M AI Governance Company | Nam Nguyen, TruthSystems (YC S25)",
    guest: "Nam Nguyen",
    company: "TruthSystems (YC S25)",
    role: "Founder, TruthSystems (YC S25)",
    tags: [],
    primaryTag: "Founders",
    desc: "Nam's co-founder was 19 years old. Law firms told them \"come back in 5 years.\" They applied to YC four times. When they finally got in, their $4M round filled in 48 hours. TruthSystems is now the AI governance layer sitting inside law firms in real time.",
    url: "episodes/24-nam-nguyen/",
    dur: "25 min",
    date: "27/03/2026",
    featured: true
  }
];

const FEATURED = EPISODES[0];

const ARCHIVE = [
  {
    guest: "Will Bodewes",
    company: "Phonely (YC S24)"
  },
  {
    guest: "Shakeel Lala",
    company: "Marloo",
    url: "episodes/27-shakeel-lala/"
  },
  {
    guest: "Nathan Yun",
    company: "Paire"
  },
  {
    guest: "Celeste Amadon",
    company: "Known",
    url: "episodes/25-celeste-amadon/"
  },
  {
    guest: "Nam Nguyen",
    company: "TruthSystems (YC S25)",
    url: "episodes/24-nam-nguyen/"
  },
  {
    guest: "Finnlay Morcombe",
    company: "Fluency"
  },
  {
    guest: "Stephen Turban",
    company: "Lumiere Education"
  },
  {
    guest: "Jevon Le Roux",
    company: "Keeyu"
  },
  {
    guest: "Ethan Yong",
    company: "Umami Papi"
  },
  {
    guest: "Andy Miller",
    company: "Heaps Normal",
    url: "episodes/19-andy-miller/"
  },
  {
    guest: "Alessia and Elia",
    company: "VibeFlow (YC S25)"
  },
  {
    guest: "Joe Zhou",
    company: "StrongRoom AI"
  },
  {
    guest: "Satya Tumati",
    company: "Socratix AI"
  },
  {
    guest: "Hamish McKay",
    company: "Order Editing"
  },
  {
    guest: "Jason Ma",
    company: "Dyna Robotics"
  },
  {
    guest: "Sam Richardson",
    company: "Butter"
  },
  {
    guest: "Phung, Daniel and Hanson",
    company: "SipHRD"
  },
  {
    guest: "Vivek and John",
    company: "Affil.ai (YC S24)"
  },
  {
    guest: "Hung Bui",
    company: "AIducation"
  },
  {
    guest: "Floriye Elmazi",
    company: "Sisterwould"
  },
  {
    guest: "Brian Pham",
    company: "Litecard"
  },
  {
    guest: "Robert Huynh",
    company: "Nook / Reforge"
  },
  {
    guest: "Ben Wood",
    company: "WipWrk"
  },
  {
    guest: "Nhi Nguyen",
    company: "MaiMoney"
  },
  {
    guest: "Kiki and Elan",
    company: "Sourmilk"
  },
  {
    guest: "Nate Spiteri",
    company: "Shopfront"
  },
  {
    guest: "Selina Li",
    company: "gymii.ai"
  },
  {
    guest: "Abby Huang",
    company: "Dime"
  }
];

const PLATFORMS = [
  {
    name: "Spotify",
    short: "SP",
    url: "https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl?si=9d89e52141e143bd",
    color: "#1DB954"
  },
  {
    name: "Apple Podcasts",
    short: "AP",
    url: "https://podcasts.apple.com/us/podcast/founders-in-motion-with-thea-ngo/id1810228671",
    color: "#FC3C44"
  },
  {
    name: "YouTube",
    short: "YT",
    url: "https://www.youtube.com/@FoundersInMotion?sub_confirmation=1",
    color: "#FF0000"
  },
  {
    name: "Instagram",
    short: "IG",
    url: "⁠⁠⁠⁠https://www.instagram.com/thea.yaps⁠⁠⁠",
    color: "#D4A87D"
  }
];

Object.assign(window, { EPISODES, FEATURED, ARCHIVE, PLATFORMS });
