/* global React */
/* GENERATED by scripts/sync.js — DO NOT EDIT BY HAND. */
/* Hand-curated content (FAQ, QUOTES, STATS, FEATURES, FILTERS) lives in data-static.jsx */
/* Generated: 2026-06-15T22:22:07.837Z */

const EPISODES = [
  {
    n: "4",
    title: "From Private Equity to Yogurt Startup Founder Story | Kiki & Elan, Sourmilk Yogurt",
    guest: "Kiki and Elan",
    company: "Sourmilk",
    role: "Co-founders, Sourmilk",
    tags: [],
    primaryTag: "Founders",
    desc: "Kiki and Elan quit their corporate jobs to start Sourmilk, a probiotic yogurt company — and grew to ten K followers and a cult following by building the brand in public. Their bet: people still care about protein, but now they're caring a lot more about gut health.",
    url: "episodes/4-kiki-and-elan/",
    dur: "31 min",
    date: "17/04/2025",
    featured: true
  },
  {
    n: "24",
    title: "How He Turned 3 YC Rejections into a $25M AI Governance Company | Nam Nguyen, TruthSystems (YC S25)",
    guest: "Nam Nguyen",
    company: "TruthSystems (YC S25)",
    role: "Founder, TruthSystems (YC S25)",
    tags: [],
    primaryTag: "Founders",
    desc: "Nam's co-founder was 19 years old. Law firms told them \"come back in 5 years.\" They applied to YC four times. When they finally got in, their $4M round filled in 48 hours. TruthSystems is now the AI governance layer sitting inside law firms in real time.",
    url: "episodes/24-nam-nguyen/",
    dur: "25 min",
    date: "27/03/2026",
    featured: true
  },
  {
    n: "14",
    title: "He's Building $600M Robots That Folds your Laundry | Jason Ma, Dyna Robotics",
    guest: "Jason Ma",
    company: "Dyna Robotics",
    role: "Founder, Dyna Robotics",
    tags: [],
    primaryTag: "Founders",
    desc: "Jason Ma turned down offers to return to Google DeepMind, Nvidia and Meta to start Dyna Robotics — and just raised $120 million to build robots that fold napkins non-stop for 24 hours instead of chasing the humanoid dream.",
    url: "episodes/14-jason-ma/",
    dur: "28 min",
    date: "25/09/2025",
    featured: true
  }
];

const FEATURED = EPISODES[0];

const ARCHIVE = [
  {
    guest: "Caroline Tran",
    company: "Hello Clever",
    url: "episodes/29-caroline-tran/"
  },
  {
    guest: "Will Bodewes",
    company: "Phonely (YC S24)",
    url: "episodes/28-will-bodewes/"
  },
  {
    guest: "Shakeel Lala",
    company: "Marloo",
    url: "episodes/27-shakeel-lala/"
  },
  {
    guest: "Nathan Yun",
    company: "Paire",
    url: "episodes/26-nathan-yun/"
  },
  {
    guest: "Celeste Amadon",
    company: "Known",
    url: "episodes/25-celeste-amadon/"
  },
  {
    guest: "Nam Nguyen",
    company: "TruthSystems (YC S25)",
    url: "episodes/24-nam-nguyen/"
  },
  {
    guest: "Finnlay Morcombe",
    company: "Fluency",
    url: "episodes/23-finnlay-morcombe/"
  },
  {
    guest: "Stephen Turban",
    company: "Lumiere Education",
    url: "episodes/22-stephen-turban/"
  },
  {
    guest: "Jevon Le Roux",
    company: "Keeyu",
    url: "episodes/21-jevon-le-roux/"
  },
  {
    guest: "Ethan Yong",
    company: "Umami Papi",
    url: "episodes/20-ethan-yong/"
  },
  {
    guest: "Andy Miller",
    company: "Heaps Normal",
    url: "episodes/19-andy-miller/"
  },
  {
    guest: "Alessia and Elia",
    company: "VibeFlow (YC S25)",
    url: "episodes/18-alessia-and-elia/"
  },
  {
    guest: "Joe Zhou",
    company: "StrongRoom AI",
    url: "episodes/17-joe-zhou/"
  },
  {
    guest: "Satya Tumati",
    company: "Socratix AI",
    url: "episodes/16-satya-tumati/"
  },
  {
    guest: "Hamish McKay",
    company: "Order Editing",
    url: "episodes/15-hamish-mckay/"
  },
  {
    guest: "Jason Ma",
    company: "Dyna Robotics",
    url: "episodes/14-jason-ma/"
  },
  {
    guest: "Sam Richardson",
    company: "Butter",
    url: "episodes/13-sam-richardson/"
  },
  {
    guest: "Phung, Daniel and Hanson",
    company: "SipHRD",
    url: "episodes/12-phung-daniel-and-hanson/"
  },
  {
    guest: "Vivek and John",
    company: "Affil.ai (YC S24)",
    url: "episodes/11-vivek-and-john/"
  },
  {
    guest: "Hung Bui",
    company: "AIducation",
    url: "episodes/10-hung-bui/"
  },
  {
    guest: "Floriye Elmazi",
    company: "Sisterwould",
    url: "episodes/9-floriye-elmazi/"
  },
  {
    guest: "Brian Pham",
    company: "Litecard",
    url: "episodes/8-brian-pham/"
  },
  {
    guest: "Robert Huynh",
    company: "Nook / Reforge",
    url: "episodes/7-robert-huynh/"
  },
  {
    guest: "Ben Wood",
    company: "WipWrk",
    url: "episodes/6-ben-wood/"
  },
  {
    guest: "Nhi Nguyen",
    company: "MaiMoney",
    url: "episodes/5-nhi-nguyen/"
  },
  {
    guest: "Kiki and Elan",
    company: "Sourmilk",
    url: "episodes/4-kiki-and-elan/"
  },
  {
    guest: "Nate Spiteri",
    company: "Shopfront",
    url: "episodes/3-nate-spiteri/"
  },
  {
    guest: "Selina Li",
    company: "gymii.ai",
    url: "episodes/2-selina-li/"
  },
  {
    guest: "Abby Huang",
    company: "Dime",
    url: "episodes/1-abby-huang/"
  }
];

const PLATFORMS = [
  {
    name: "Spotify",
    short: "SP",
    url: "https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl?si=9d89e52141e143bd",
    color: "#1DB954"
  },
  {
    name: "Apple Podcasts",
    short: "AP",
    url: "https://podcasts.apple.com/us/podcast/founders-in-motion-with-thea-ngo/id1810228671",
    color: "#FC3C44"
  },
  {
    name: "YouTube",
    short: "YT",
    url: "https://www.youtube.com/@FoundersInMotion?sub_confirmation=1",
    color: "#FF0000"
  },
  {
    name: "Instagram",
    short: "IG",
    url: "https://www.instagram.com/thea.yaps",
    color: "#D4A87D"
  }
];

Object.assign(window, { EPISODES, FEATURED, ARCHIVE, PLATFORMS });
