/* global React */
/* GENERATED by scripts/sync.js — DO NOT EDIT BY HAND. */
/* Hand-curated content (QUOTES, STATS, FEATURES) lives in data-static.jsx */
/* Generated: 2026-08-05T14:00:22.515Z */

const EPISODES = [
  {
    n: "10",
    title: "What Stanford Didn't Teach Me: Rebuilding Vietnam's Hottest EdTech | Hung Bui, AIducation",
    guest: "Hung Bui",
    company: "AIducation",
    role: "Founder, AIducation",
    tags: [],
    primaryTag: "Founders",
    desc: "Hung Bui's AIducation hit 40,000 users and entered 23,000 schools — but only after his first product flopped in the field and he had five months to rebuild it from scratch.",
    url: "episodes/10-hung-bui/",
    dur: "25 min",
    date: "Oct 7, 2025",
    featured: true
  },
  {
    n: "7",
    title: "Why this YC-backed Startup Really Failed | Robert Huynh, Nook (YC W22)",
    guest: "Robert Huynh",
    company: "Nook / Reforge",
    role: "Co-founder, Nook (now Reforge Labs)",
    tags: [],
    primaryTag: "Founders",
    desc: "Robert Huynh got Nook, his blue collar job marketplace in Vietnam, to 50,000 users and a $20 million valuation — then had to walk away. This is the story of how it started and how it fell apart.",
    url: "episodes/7-robert-huynh/",
    dur: "32 min",
    date: "29/05/2025",
    featured: true
  },
  {
    n: "14",
    title: "He's Building $600M Robots That Folds your Laundry | Jason Ma, Dyna Robotics",
    guest: "Jason Ma",
    company: "Dyna Robotics",
    role: "Founder, Dyna Robotics",
    tags: [],
    primaryTag: "Founders",
    desc: "Jason Ma turned down offers to return to Google DeepMind, Nvidia and Meta to start Dyna Robotics — and just raised $120 million to build robots that fold napkins non-stop for 24 hours instead of chasing the humanoid dream.",
    url: "episodes/14-jason-ma/",
    dur: "28 min",
    date: "25/09/2025",
    featured: true
  }
];

const FEATURED = EPISODES[0];

const ARCHIVE = [
  {
    guest: "Josh Foreman",
    company: "InDebted",
    url: "episodes/32-josh-foreman/"
  },
  {
    guest: "Rakhesh Martyn",
    company: "Hachiko Energy",
    url: "episodes/31-rakhesh-martyn/"
  },
  {
    guest: "Lauren Barker",
    company: "Good Mind Therapeutics",
    url: "episodes/30-lauren-barker/"
  },
  {
    guest: "Caroline Tran",
    company: "Hello Clever",
    url: "episodes/29-caroline-tran/"
  },
  {
    guest: "Will Bodewes",
    company: "Phonely (YC S24)",
    url: "episodes/28-will-bodewes/"
  },
  {
    guest: "Shakeel Lala",
    company: "Marloo",
    url: "episodes/27-shakeel-lala/"
  },
  {
    guest: "Nathan Yun",
    company: "Paire",
    url: "episodes/26-nathan-yun/"
  },
  {
    guest: "Celeste Amadon",
    company: "Known",
    url: "episodes/25-celeste-amadon/"
  },
  {
    guest: "Nam Nguyen",
    company: "TruthSystems (YC S25)",
    url: "episodes/24-nam-nguyen/"
  },
  {
    guest: "Finnlay Morcombe",
    company: "Fluency",
    url: "episodes/23-finnlay-morcombe/"
  },
  {
    guest: "Stephen Turban",
    company: "Lumiere Education",
    url: "episodes/22-stephen-turban/"
  },
  {
    guest: "Jevon Le Roux",
    company: "Keeyu",
    url: "episodes/21-jevon-le-roux/"
  },
  {
    guest: "Ethan Yong",
    company: "Umami Papi",
    url: "episodes/20-ethan-yong/"
  },
  {
    guest: "Andy Miller",
    company: "Heaps Normal",
    url: "episodes/19-andy-miller/"
  },
  {
    guest: "Alessia and Elia",
    company: "VibeFlow (YC S25)",
    url: "episodes/18-alessia-and-elia/"
  },
  {
    guest: "Joe Zhou",
    company: "StrongRoom AI",
    url: "episodes/17-joe-zhou/"
  },
  {
    guest: "Satya Tumati",
    company: "Socratix AI",
    url: "episodes/16-satya-tumati/"
  },
  {
    guest: "Hamish McKay",
    company: "Order Editing",
    url: "episodes/15-hamish-mckay/"
  },
  {
    guest: "Jason Ma",
    company: "Dyna Robotics",
    url: "episodes/14-jason-ma/"
  },
  {
    guest: "Sam Richardson",
    company: "Butter",
    url: "episodes/13-sam-richardson/"
  },
  {
    guest: "Phung, Daniel and Hanson",
    company: "SipHRD",
    url: "episodes/12-phung-daniel-and-hanson/"
  },
  {
    guest: "Vivek and John",
    company: "Affil.ai (YC S24)",
    url: "episodes/11-vivek-and-john/"
  },
  {
    guest: "Hung Bui",
    company: "AIducation",
    url: "episodes/10-hung-bui/"
  },
  {
    guest: "Floriye Elmazi",
    company: "Sisterwould",
    url: "episodes/9-floriye-elmazi/"
  },
  {
    guest: "Brian Pham",
    company: "Litecard",
    url: "episodes/8-brian-pham/"
  },
  {
    guest: "Robert Huynh",
    company: "Nook / Reforge",
    url: "episodes/7-robert-huynh/"
  },
  {
    guest: "Ben Wood",
    company: "WipWrk",
    url: "episodes/6-ben-wood/"
  },
  {
    guest: "Nhi Nguyen",
    company: "MaiMoney",
    url: "episodes/5-nhi-nguyen/"
  },
  {
    guest: "Kiki and Elan",
    company: "Sourmilk",
    url: "episodes/4-kiki-and-elan/"
  },
  {
    guest: "Nate Spiteri",
    company: "Shopfront",
    url: "episodes/3-nate-spiteri/"
  },
  {
    guest: "Selina Li",
    company: "gymii.ai",
    url: "episodes/2-selina-li/"
  },
  {
    guest: "Abby Huang",
    company: "Dime",
    url: "episodes/1-abby-huang/"
  }
];

const PLATFORMS = [
  {
    name: "Spotify",
    short: "SP",
    url: "https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl?si=9d89e52141e143bd",
    color: "#1DB954"
  },
  {
    name: "Apple Podcasts",
    short: "AP",
    url: "https://podcasts.apple.com/us/podcast/founders-in-motion-with-thea-ngo/id1810228671",
    color: "#FC3C44"
  },
  {
    name: "YouTube",
    short: "YT",
    url: "https://www.youtube.com/@FoundersInMotion?sub_confirmation=1",
    color: "#FF0000"
  },
  {
    name: "Instagram",
    short: "IG",
    url: "https://www.instagram.com/thea.yaps",
    color: "#D4A87D"
  }
];

Object.assign(window, { EPISODES, FEATURED, ARCHIVE, PLATFORMS });
