/**
 * Render data.jsx (homepage React content) and episodes/index.html (archive page)
 * from sheet rows + parsed content docs.
 *
 * Two arrays drive the homepage:
 *   - EPISODES  : top featured cards (max 3). Episode is featured if its
 *                 sheet row marks it featured, OR it's the 3 most recent
 *                 that have a content doc.
 *   - ARCHIVE   : every episode, oldest → newest (or by episode_number desc).
 *
 * Static content (FAQ, QUOTES, FEATURES, STATS, FILTERS, PLATFORMS) lives in
 * data-static.jsx, hand-edited, never touched by sync.
 */

const ESC_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, c => ESC_MAP[c]); }
function escAttr(s) { return esc(s); }

/**
 * Serialize a JS object literal with double-quoted keys and string values.
 * Booleans, numbers, and nested arrays pass through.
 */
function jsLiteral(v, indent = 2, depth = 0) {
  const pad = ' '.repeat(indent * (depth + 1));
  const padOuter = ' '.repeat(indent * depth);
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    const items = v.map(x => pad + jsLiteral(x, indent, depth + 1));
    return '[\n' + items.join(',\n') + '\n' + padOuter + ']';
  }
  if (typeof v === 'object') {
    const keys = Object.keys(v);
    if (keys.length === 0) return '{}';
    const props = keys.map(k => `${pad}${k}: ${jsLiteral(v[k], indent, depth + 1)}`);
    return '{\n' + props.join(',\n') + '\n' + padOuter + '}';
  }
  return JSON.stringify(v);
}

function formatShortDate(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function pickFeatured(episodes, n = 3) {
  const explicit = episodes.filter(e => e.featured);
  if (explicit.length >= n) return explicit.slice(0, n);
  const withPage = episodes
    .filter(e => e.has_episode_page && !e.featured)
    .sort((a, b) => b.episode_number - a.episode_number);
  return [...explicit, ...withPage].slice(0, n);
}

/**
 * Render data.jsx.
 * `episodes` is the merged list of sheet rows + parsed content.
 */
export function renderDataCMS({ episodes, settings }) {
  const sortedDesc = [...episodes].sort((a, b) => b.episode_number - a.episode_number);
  const featured = pickFeatured(sortedDesc, 3);

  const EPISODES = featured.map(e => ({
    n: String(e.episode_number),
    title: e.title,
    guest: e.guest_name,
    company: e.guest_company,
    role: e.role || (e.guest_company ? `Founder, ${e.guest_company}` : 'Founder'),
    tags: e.tags || [],
    primaryTag: (e.tags && e.tags[0]) || 'Founders',
    desc: e.short_desc || e.hook || '',
    url: e.has_episode_page ? `episodes/${e.slug}/` : (e.spotify_url || ''),
    dur: e.duration || '',
    date: formatShortDate(e.published_date),
    featured: true,
  }));

  const ARCHIVE = sortedDesc.map(e => {
    const row = { guest: e.guest_name, company: e.guest_company };
    if (e.has_episode_page) row.url = `episodes/${e.slug}/`;
    return row;
  });

  const PLATFORMS = [
    { name: 'Spotify',         short: 'SP', url: settings.spotify_show   || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl', color: '#1DB954' },
    { name: 'Apple Podcasts',  short: 'AP', url: settings.apple_show     || 'https://podcasts.apple.com/us/podcast/founders-in-motion/id1810228671', color: '#FC3C44' },
    { name: 'YouTube',         short: 'YT', url: settings.youtube_channel|| '#', color: '#FF0000' },
    { name: 'Instagram',       short: 'IG', url: settings.instagram      || 'https://www.instagram.com/foundersinmotion/', color: '#D4A87D' },
  ];

  const generatedAt = new Date().toISOString();

  return `/* global React */
/* GENERATED by scripts/sync.js — DO NOT EDIT BY HAND. */
/* Hand-curated content (FAQ, QUOTES, STATS, FEATURES, FILTERS) lives in data-static.jsx */
/* Generated: ${generatedAt} */

const EPISODES = ${jsLiteral(EPISODES)};

const FEATURED = EPISODES[0];

const ARCHIVE = ${jsLiteral(ARCHIVE)};

const PLATFORMS = ${jsLiteral(PLATFORMS)};

Object.assign(window, { EPISODES, FEATURED, ARCHIVE, PLATFORMS });
`;
}

/**
 * Render episodes/index.html — featured grid + full archive rows.
 *
 * Assumes the standalone HTML page already has the head/nav/footer chrome.
 * We only generate the contents of <main class="index-page"> innerHTML.
 *
 * To keep this simple and avoid breaking the existing nav/footer, we emit a
 * full standalone HTML document mirroring the structure of episodes/index.html.
 */
export function renderArchivePage({ episodes, settings }) {
  const sortedDesc = [...episodes].sort((a, b) => b.episode_number - a.episode_number);
  const featured = pickFeatured(sortedDesc, 4);
  const featuredIds = new Set(featured.map(e => e.episode_number));
  const archive = sortedDesc.filter(e => !featuredIds.has(e.episode_number));

  const generatedAt = new Date().toISOString();
  const totalCount = episodes.length;

  const featuredCards = featured.map(e => {
    const primaryTag = (e.tags && e.tags[0]) || 'Founders';
    const role = e.role || (e.guest_company ? `Co-founder, ${e.guest_company}` : 'Founder');
    return `      <a href="${esc(e.slug)}/" class="featured-card">
        <span class="fc-arrow">↗</span>
        <div class="num-tag">Episode ${e.episode_number} · ${esc(primaryTag)}</div>
        <h3>${esc(e.title)}</h3>
        <p class="fc-desc">${esc(e.short_desc || e.hook || '')}</p>
        <div class="fc-guest">
          <div class="fc-avatar">${esc(initials(e.guest_name))}</div>
          <div class="fc-guest-meta">
            <b>${esc(e.guest_name)}</b>
            <i>${esc(role)}</i>
          </div>
        </div>
      </a>`;
  }).join('\n\n');

  const archiveRows = archive.map(e => {
    const href = e.has_episode_page ? `${esc(e.slug)}/` : (esc(e.spotify_url) || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl');
    const metaLabel = e.has_episode_page ? 'Show notes ↗' : 'Spotify ↗';
    return `      <a href="${href}" class="ep-row">
        <div class="ep-row-num">${e.episode_number}</div>
        <div class="ep-row-content">
          <h4>${esc(e.title)}</h4>
          <p>${esc(e.short_desc || e.hook || `${e.guest_name} on Founders In Motion.`)}</p>
        </div>
        <div class="ep-row-guest"><b>${esc(e.guest_name)}</b><i>${esc(e.guest_company)}</i></div>
        <div class="ep-row-meta">${metaLabel}</div>
      </a>`;
  }).join('\n\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Episodes — Founders In Motion | All ${totalCount} Episodes</title>
<meta name="description" content="All episodes of Founders In Motion. ${totalCount} unscripted conversations with early-stage founders across Australia, Southeast Asia, and the US — covering customer discovery, pre-seed fundraising, pivots, rebuilds, and what the messy middle of building actually looks like." />
<link rel="canonical" href="https://foundersinmotion.com/episodes/" />
<meta property="og:url" content="https://foundersinmotion.com/episodes/" />
<meta property="og:site_name" content="Founders In Motion" />
<meta property="og:image" content="https://foundersinmotion.com/assets/youtube-banner.png" />
<meta name="twitter:card" content="summary_large_image" />

<meta property="og:title" content="All Episodes — Founders In Motion" />
<meta property="og:description" content="${totalCount} founders. The messy middle of building, on tape." />
<meta property="og:type" content="website" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700;800;900&family=Inter:wght@400;500;600;700&family=Playfair+Display:ital,wght@1,400;1,500&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="../styles.css" />
<link rel="stylesheet" href="../episodes-archive.css" />

<!-- Generated: ${generatedAt} -->

</head>
<body>

<nav class="nav">
  <div class="container nav-inner">
    <a href="../index.html" class="brand">
      <img class="brand-logo" src="../assets/logo-white.png" alt="Founders In Motion" />
      <span class="brand-text">Founders <em>In Motion</em></span>
    </a>
    <div class="nav-links">
      <a href="../index.html#episodes">Episodes</a>
      <a href="../index.html#faq">Founder Questions</a>
      <a href="../index.html#about">About</a>
    </div>
    <a class="btn btn-primary" href="${escAttr(settings.spotify_show || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl')}">
      Listen Free <span aria-hidden="true">→</span>
    </a>
  </div>
</nav>

<main class="index-page">
  <div class="container">

    <header class="index-head">
      <div class="label">Episodes</div>
      <h1>${totalCount} founders. The messy middle, on tape.</h1>
      <p>Unscripted conversations with early-stage founders across Australia, Southeast Asia, and the US. Each episode is one founder, still in the thick of it, answering the questions an early-stage investor would actually ask.</p>
    </header>

    <div class="section-label">Featured episodes — full show notes</div>

    <div class="featured-grid">

${featuredCards}

    </div>

    <div class="section-label">The full archive</div>

    <div class="ep-list">

${archiveRows}

    </div>

  </div>
</main>

<footer>
  <div class="container">
    <div class="footer-row">
      <a href="../index.html" class="brand">
        <img class="brand-logo" src="../assets/logo-white.png" alt="Founders In Motion" style="height: 24px;" />
        <span class="brand-text">Founders <em>In Motion</em></span>
      </a>
      <nav class="footer-nav">
        <a href="${escAttr(settings.spotify_show || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl')}">Spotify</a>
        <a href="${escAttr(settings.apple_show || 'https://podcasts.apple.com/us/podcast/founders-in-motion/id1810228671')}">Apple</a>
        <a href="${escAttr(settings.instagram || 'https://www.instagram.com/foundersinmotion/')}">Instagram</a>
        <a href="${escAttr(settings.tiktok || 'https://www.tiktok.com/@foundersinmotion')}">TikTok</a>
        <a href="${escAttr(settings.my_linkedin || 'https://www.linkedin.com/in/theango/')}">LinkedIn</a>
      </nav>
      <div class="copyright">© ${new Date().getFullYear()} Founders In Motion · Hosted by Thea Ngo</div>
    </div>
    <div class="footer-mark">Founders <em>In Motion</em></div>
  </div>
</footer>

</body>
</html>
`;
}

function initials(name) {
  if (!name) return '??';
  const parts = name.replace(/[&]/g, ' ').split(/\s+/).filter(Boolean);
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}
