/**
 * Render data.jsx (homepage React content) and episodes/index.html (archive page)
 * from sheet rows + parsed content docs.
 *
 * Two arrays drive the homepage:
 *   - EPISODES  : top featured cards (max 3). Episode is featured if its
 *                 sheet row marks it featured, OR it's the 3 most recent
 *                 that have a content doc.
 *   - ARCHIVE   : every episode, oldest → newest (or by episode_number desc).
 *
 * Static content (FAQ, QUOTES, FEATURES, STATS, FILTERS, PLATFORMS) lives in
 * data-static.jsx, hand-edited, never touched by sync.
 */

import fs from 'fs';

const ESC_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, c => ESC_MAP[c]); }
function escAttr(s) { return esc(s); }

/**
 * Serialize a JS object literal with double-quoted keys and string values.
 * Booleans, numbers, and nested arrays pass through.
 */
function jsLiteral(v, indent = 2, depth = 0) {
  const pad = ' '.repeat(indent * (depth + 1));
  const padOuter = ' '.repeat(indent * depth);
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    const items = v.map(x => pad + jsLiteral(x, indent, depth + 1));
    return '[\n' + items.join(',\n') + '\n' + padOuter + ']';
  }
  if (typeof v === 'object') {
    const keys = Object.keys(v);
    if (keys.length === 0) return '{}';
    const props = keys.map(k => `${pad}${k}: ${jsLiteral(v[k], indent, depth + 1)}`);
    return '{\n' + props.join(',\n') + '\n' + padOuter + '}';
  }
  return JSON.stringify(v);
}

function formatShortDate(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function pickFeatured(episodes, n = 3) {
  const explicit = episodes.filter(e => e.featured);
  if (explicit.length >= n) return explicit.slice(0, n);
  const withPage = episodes
    .filter(e => e.has_episode_page && !e.featured)
    .sort((a, b) => b.episode_number - a.episode_number);
  return [...explicit, ...withPage].slice(0, n);
}

/**
 * Render data.jsx.
 * `episodes` is the merged list of sheet rows + parsed content.
 */
// Homepage "Start here" trio — the best-performing episodes, in display order.
// Editorial pick (not recency): edit these slugs to swap which 3 show on the homepage.
const START_HERE_SLUGS = ['4-kiki-and-elan', '24-nam-nguyen', '14-jason-ma'];

export function renderDataCMS({ episodes, settings }) {
  const sortedDesc = [...episodes].sort((a, b) => b.episode_number - a.episode_number);
  // Prefer the curated "Start here" trio; fall back to featured/most-recent if any slug is missing.
  const bySlug = new Map(sortedDesc.map(e => [e.slug, e]));
  const curated = START_HERE_SLUGS.map(s => bySlug.get(s)).filter(Boolean);
  const featured = curated.length === START_HERE_SLUGS.length ? curated : pickFeatured(sortedDesc, 3);

  const EPISODES = featured.map(e => ({
    n: String(e.episode_number),
    title: e.title,
    guest: e.guest_name,
    company: e.guest_company,
    role: e.role || (e.guest_company ? `Founder, ${e.guest_company}` : 'Founder'),
    tags: e.tags || [],
    primaryTag: (e.tags && e.tags[0]) || 'Founders',
    desc: e.short_desc || e.hook || '',
    url: e.has_episode_page ? `episodes/${e.slug}/` : (e.spotify_url || ''),
    dur: e.duration || '',
    date: formatShortDate(e.published_date),
    featured: true,
  }));

  const ARCHIVE = sortedDesc.map(e => {
    const row = { guest: e.guest_name, company: e.guest_company };
    if (e.has_episode_page) row.url = `episodes/${e.slug}/`;
    return row;
  });

  const PLATFORMS = [
    { name: 'Spotify',         short: 'SP', url: settings.spotify_show   || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl', color: '#1DB954' },
    { name: 'Apple Podcasts',  short: 'AP', url: settings.apple_show     || 'https://podcasts.apple.com/us/podcast/founders-in-motion/id1810228671', color: '#FC3C44' },
    { name: 'YouTube',         short: 'YT', url: settings.youtube_channel|| '#', color: '#FF0000' },
    { name: 'Instagram',       short: 'IG', url: settings.instagram      || 'https://www.instagram.com/thea.yaps', color: '#D4A87D' },
  ];

  const generatedAt = new Date().toISOString();

  return `/* global React */
/* GENERATED by scripts/sync.js — DO NOT EDIT BY HAND. */
/* Hand-curated content (FAQ, QUOTES, STATS, FEATURES, FILTERS) lives in data-static.jsx */
/* Generated: ${generatedAt} */

const EPISODES = ${jsLiteral(EPISODES)};

const FEATURED = EPISODES[0];

const ARCHIVE = ${jsLiteral(ARCHIVE)};

const PLATFORMS = ${jsLiteral(PLATFORMS)};

Object.assign(window, { EPISODES, FEATURED, ARCHIVE, PLATFORMS });
`;
}

/**
 * Render episodes/index.html — featured grid + full archive rows.
 *
 * Assumes the standalone HTML page already has the head/nav/footer chrome.
 * We only generate the contents of <main class="index-page"> innerHTML.
 *
 * To keep this simple and avoid breaking the existing nav/footer, we emit a
 * full standalone HTML document mirroring the structure of episodes/index.html.
 */
export function renderArchivePage({ episodes, settings }) {
  const sortedDesc = [...episodes].sort((a, b) => b.episode_number - a.episode_number);
  const featured = pickFeatured(sortedDesc, 1);
  const featuredIds = new Set(featured.map(e => e.episode_number));
  const grid = sortedDesc.filter(e => !featuredIds.has(e.episode_number));

  const generatedAt = new Date().toISOString();
  const totalCount = episodes.length;

  // Resolve the destination + a friendly "watch/listen" label for any episode.
  const linkFor = (e) => e.has_episode_page
    ? `${esc(e.slug)}/`
    : (esc(e.spotify_url) || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl');

  // ---- Featured / most-recent hero card (wide, with large thumbnail) ----
  const featuredCards = featured.map(e => {
    const primaryTag = (e.tags && e.tags[0]) || 'Founders';
    const desc = e.short_desc || e.hook || `${e.guest_name} on Founders In Motion.`;
    return `      <a href="${linkFor(e)}" class="ep-feature">
        <div class="ep-feature-media">
          <img src="${thumbUrl(e)}" alt="${escAttr(e.guest_name)} — Founders In Motion episode ${e.episode_number}" loading="lazy" decoding="async" />
          <span class="ep-badge ep-badge-lg">EP ${e.episode_number}</span>
          <span class="ep-feature-flag">Latest</span>
        </div>
        <div class="ep-feature-body">
          <div class="ep-kicker">${esc(primaryTag)}</div>
          <h2>${esc(e.title)}</h2>
          <p class="ep-feature-desc">${esc(desc)}</p>
          <div class="ep-guest">
            <b>${esc(e.guest_name)}</b>
            ${e.guest_company ? `<i>${esc(e.guest_company)}</i>` : ''}
          </div>
          <span class="ep-feature-cta">${e.has_episode_page ? 'Show notes' : 'Listen on Spotify'} <span aria-hidden="true">→</span></span>
        </div>
      </a>`;
  }).join('\n\n');

  // ---- The full grid of every other episode ----
  const gridCards = grid.map(e => {
    const desc = e.short_desc || e.hook || `${e.guest_name} on Founders In Motion.`;
    return `      <a href="${linkFor(e)}" class="ep-card">
        <div class="ep-card-media">
          <img src="${thumbUrl(e)}" alt="${escAttr(e.guest_name)} — Founders In Motion episode ${e.episode_number}" loading="lazy" decoding="async" />
          <span class="ep-badge">EP ${e.episode_number}</span>
        </div>
        <div class="ep-card-body">
          <h3 class="ep-card-guest">${esc(e.guest_name)}</h3>
          ${e.guest_company ? `<div class="ep-card-company">${esc(e.guest_company)}</div>` : ''}
          <p class="ep-card-hook">${esc(desc)}</p>
        </div>
      </a>`;
  }).join('\n\n');

  // ---- Collection structured data (BreadcrumbList + ItemList of every episode page) ----
  const SITE = 'https://foundersinmotion.tech';
  const epPages = sortedDesc.filter(e => e.has_episode_page);
  const itemListSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'Founders In Motion — All Episodes',
    itemListElement: epPages.map((e, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      url: `${SITE}/episodes/${e.slug}/`,
      name: e.title || `${e.guest_name}${e.guest_company ? ' — ' + e.guest_company : ''}`,
    })),
  }, null, 2);
  const breadcrumbSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Founders In Motion', item: `${SITE}/` },
      { '@type': 'ListItem', position: 2, name: 'Episodes', item: `${SITE}/episodes/` },
    ],
  }, null, 2);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
<meta name="author" content="Thea Ngo" />
<title>Episodes — Founders In Motion | All ${totalCount} Episodes</title>
<meta name="description" content="All episodes of Founders In Motion. ${totalCount} unscripted conversations with early-stage founders across Australia, Southeast Asia, and the US — covering customer discovery, pre-seed fundraising, pivots, rebuilds, and what the messy middle of building actually looks like." />
<link rel="canonical" href="https://foundersinmotion.tech/episodes/" />
<meta property="og:url" content="https://foundersinmotion.tech/episodes/" />
<meta property="og:site_name" content="Founders In Motion" />
<meta property="og:image" content="https://foundersinmotion.tech/assets/youtube-banner.png" />
<meta name="twitter:card" content="summary_large_image" />

<meta property="og:title" content="All Episodes — Founders In Motion" />
<meta property="og:description" content="${totalCount} founders. The messy middle of building, on tape." />
<meta property="og:type" content="website" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700;800;900&family=Inter:wght@400;500;600;700&family=Playfair+Display:ital,wght@1,400;1,500&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="../styles.css" />
<link rel="stylesheet" href="../episodes-archive.css" />

<!-- JSON-LD: BreadcrumbList -->
<script type="application/ld+json">
${breadcrumbSchema}
</script>

<!-- JSON-LD: ItemList of every episode -->
<script type="application/ld+json">
${itemListSchema}
</script>

<style>
  /* ── Episodes archive: visual card grid (scoped, tokens from styles.css) ── */
  .ep-feature {
    display: grid;
    grid-template-columns: 1.15fr 1fr;
    gap: 0;
    border: 1px solid var(--border);
    border-radius: 20px;
    overflow: hidden;
    background: rgba(255,255,255,0.02);
    text-decoration: none;
    margin-bottom: 88px;
    transition: border-color .18s ease, transform .18s ease, box-shadow .18s ease;
  }
  .ep-feature:hover {
    border-color: var(--cream);
    transform: translateY(-3px);
    box-shadow: 0 18px 50px -22px rgba(0,0,0,0.7);
  }
  .ep-feature-media {
    position: relative;
    background: var(--surface);
    overflow: hidden;
  }
  .ep-feature-media img,
  .ep-card-media img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
    transition: transform .35s ease;
  }
  .ep-feature-media img {
    position: absolute;
    inset: 0;
  }
  .ep-feature:hover .ep-feature-media img,
  .ep-card:hover .ep-card-media img { transform: scale(1.04); }
  .ep-feature-body {
    padding: clamp(28px, 3vw, 44px);
    display: flex;
    flex-direction: column;
    justify-content: center;
  }
  .ep-kicker {
    font-family: var(--body);
    font-size: 11px; font-weight: 700;
    letter-spacing: 0.12em; text-transform: uppercase;
    color: var(--cream);
    margin-bottom: 14px;
  }
  .ep-feature-body h2 {
    font-family: var(--sans);
    font-weight: 800;
    font-size: clamp(24px, 2.6vw, 34px);
    line-height: 1.12;
    letter-spacing: -0.025em;
    margin: 0 0 16px;
    color: var(--off-white);
    text-wrap: balance;
  }
  .ep-feature-desc {
    font-size: 15px; line-height: 1.6;
    color: var(--off-white);
    margin: 0 0 22px;
    max-width: 48ch;
  }
  .ep-feature-cta {
    margin-top: 8px;
    font-family: var(--body);
    font-size: 14px; font-weight: 600;
    color: var(--cream);
  }
  .ep-feature:hover .ep-feature-cta span { transform: translateX(3px); }
  .ep-feature-cta span { display: inline-block; transition: transform .18s ease; }
  .ep-feature-flag {
    position: absolute;
    top: 14px; right: 14px;
    padding: 4px 11px;
    border-radius: 999px;
    background: var(--cream);
    color: var(--forest);
    font-family: var(--sans);
    font-size: 10px; font-weight: 800;
    letter-spacing: 0.1em; text-transform: uppercase;
  }

  /* ── Card grid ── */
  .ep-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 24px;
  }
  .ep-card {
    display: flex;
    flex-direction: column;
    border: 1px solid var(--border);
    border-radius: 16px;
    overflow: hidden;
    background: rgba(255,255,255,0.02);
    text-decoration: none;
    transition: border-color .18s ease, transform .18s ease, box-shadow .18s ease;
  }
  .ep-card:hover {
    border-color: var(--cream);
    transform: translateY(-3px);
    box-shadow: 0 16px 40px -24px rgba(0,0,0,0.7);
  }
  .ep-card-media {
    position: relative;
    aspect-ratio: 16 / 9;
    background: var(--surface);
    overflow: hidden;
  }
  .ep-badge {
    position: absolute;
    bottom: 12px; left: 12px;
    padding: 4px 10px;
    border-radius: 8px;
    background: rgba(12,12,12,0.78);
    backdrop-filter: blur(4px);
    color: var(--cream);
    font-family: var(--sans);
    font-size: 11px; font-weight: 800;
    letter-spacing: 0.06em;
    font-variant-numeric: tabular-nums;
  }
  .ep-badge-lg {
    top: 14px; left: 14px; bottom: auto;
    font-size: 12px;
    padding: 5px 12px;
  }
  .ep-card-body {
    padding: 20px;
    display: flex;
    flex-direction: column;
    flex: 1;
  }
  .ep-card-guest {
    font-family: var(--sans);
    font-weight: 800;
    font-size: 18px;
    letter-spacing: -0.02em;
    line-height: 1.2;
    margin: 0 0 3px;
    color: var(--off-white);
  }
  .ep-card:hover .ep-card-guest { color: var(--cream); }
  .ep-card-company {
    font-family: var(--body);
    font-size: 13px;
    color: var(--cream);
    margin-bottom: 12px;
  }
  .ep-card-hook {
    margin: 0;
    font-size: 14px;
    line-height: 1.55;
    color: var(--muted);
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  @media (max-width: 800px) {
    .ep-feature { grid-template-columns: 1fr; }
    .ep-feature-media { aspect-ratio: 16 / 9; }
    .ep-feature-media img { position: static; inset: auto; }
    .ep-grid { grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 18px; }
  }
  @media (max-width: 520px) {
    .ep-grid { grid-template-columns: 1fr; }
  }
</style>

<!-- Generated: ${generatedAt} -->

</head>
<body>

<nav class="nav">
  <div class="container nav-inner">
    <a href="../index.html" class="brand">
      <img class="brand-logo" src="../assets/logo-white.png" alt="Founders In Motion" />
      <span class="brand-text">Founders <em>In Motion</em></span>
    </a>
    <div class="nav-links">
      <a href="../index.html#episodes">Episodes</a>
      <a href="../index.html#faq">Founder Questions</a>
      <a href="../index.html#about">About</a>
    </div>
    <a class="btn btn-primary" href="${escAttr(settings.spotify_show || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl')}">
      Listen Free <span aria-hidden="true">→</span>
    </a>
  </div>
</nav>

<main class="index-page">
  <div class="container">

    <header class="index-head">
      <div class="label">Episodes</div>
      <h1>${totalCount} founders. The messy middle, on tape.</h1>
      <p>Unscripted conversations with early-stage founders across Australia, Southeast Asia, and the US. Each episode is one founder, still in the thick of it, answering the questions an early-stage investor would actually ask.</p>
    </header>

    <div class="section-label">Latest episode</div>

${featuredCards}

    <div class="section-label">All episodes</div>

    <div class="ep-grid">

${gridCards}

    </div>

  </div>
</main>

<footer>
  <div class="container">
    <div class="footer-row">
      <a href="../index.html" class="brand">
        <img class="brand-logo" src="../assets/logo-white.png" alt="Founders In Motion" style="height: 24px;" />
        <span class="brand-text">Founders <em>In Motion</em></span>
      </a>
      <nav class="footer-nav">
        <a href="${escAttr(settings.spotify_show || 'https://open.spotify.com/show/0ZwlHrWLbX6ajZo2hsVVdl')}">Spotify</a>
        <a href="${escAttr(settings.apple_show || 'https://podcasts.apple.com/us/podcast/founders-in-motion/id1810228671')}">Apple</a>
        <a href="${escAttr(settings.instagram || 'https://www.instagram.com/thea.yaps')}">Instagram</a>
        <a href="${escAttr(settings.tiktok || 'https://www.tiktok.com/@foundersinmotion')}">TikTok</a>
        <a href="${escAttr(settings.my_linkedin || 'https://www.linkedin.com/in/theango/')}">LinkedIn</a>
      </nav>
      <div class="copyright">© ${new Date().getFullYear()} Founders In Motion · Hosted by Thea Ngo</div>
    </div>
    <div class="footer-mark">Founders <em>In Motion</em></div>
  </div>
</footer>

</body>
</html>
`;
}

/** Extract a YouTube video id from a watch / youtu.be / embed URL. Mirrors sync.js. */
function getYouTubeId(url) {
  if (!url) return null;
  const match = String(url).match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([a-zA-Z0-9_-]{11})/);
  return match ? match[1] : null;
}

/** Cover-image URL for an episode: custom thumbnail, else YouTube, else brand banner. */
function thumbUrl(e) {
  if (e.slug && fs.existsSync(`assets/thumbs/${e.slug}.jpg`)) return `/assets/thumbs/${e.slug}.jpg`;
  const id = getYouTubeId(e.youtube_url);
  return id ? `https://i.ytimg.com/vi/${id}/hqdefault.jpg` : '/assets/youtube-banner.png';
}

