#!/usr/bin/env node
/**
 * build-client.mjs — compile the homepage client into a single app.bundle.js so
 * the browser no longer downloads @babel/standalone (~3MB) and transpiles JSX at
 * runtime.
 *
 * The four client files load in this exact order today. Two (sections.jsx,
 * app.jsx) contain JSX and get transpiled with @babel/preset-react (classic
 * runtime, so they use the global React.createElement — same as the in-browser
 * babel did). Two (data-static.jsx, data.jsx) are plain data JS with no JSX and
 * pass through verbatim. Everything is concatenated in order into ONE
 * global-scope script, which behaves identically to separate <script> tags.
 *
 * Run locally after editing any of the .jsx files:  node scripts/build-client.mjs
 * CI runs it after every sync (data.jsx is regenerated by sync.js).
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import babel from '@babel/core';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Same order as the <script> tags in index.html. jsx:true -> transpile.
const FILES = [
  { f: 'data-static.jsx', jsx: false },
  { f: 'data.jsx', jsx: false },
  { f: 'sections.jsx', jsx: true },
  { f: 'app.jsx', jsx: true },
];

// Each file currently has its own `const { useState, useEffect } = React;`. As
// separate <script>s that's fine, but concatenated into one scope it's a redeclare
// error. Strip those lines from every file and hoist ONE combined declaration to
// the top of the bundle (binds to the same React.* hooks — behaviour is identical).
const reactHooks = new Set();
const stripReactDestructure = (c) =>
  c.replace(/^[ \t]*const\s*\{([^}]*)\}\s*=\s*React;[ \t]*\r?\n?/gm, (_m, names) => {
    names.split(',').forEach((n) => { const t = n.trim(); if (t) reactHooks.add(t); });
    return '';
  });

let body = '';
for (const { f, jsx } of FILES) {
  const src = fs.readFileSync(path.join(root, f), 'utf8');
  let code = src;
  if (jsx) {
    code = babel.transformSync(src, {
      filename: f,
      presets: [['@babel/preset-react', { runtime: 'classic' }]],
      compact: false,
      comments: false,
      babelrc: false,
      configFile: false,
    }).code;
  }
  code = stripReactDestructure(code);
  // Leading ';' guards against ASI edge cases when concatenating files.
  body += `\n;/* ===== ${f} ===== */\n${code}\n`;
}

const header =
  '/* AUTO-GENERATED by scripts/build-client.mjs — do not edit. Edit the .jsx sources. */\n' +
  (reactHooks.size ? `const { ${[...reactHooks].join(', ')} } = React;\n` : '');

const dest = path.join(root, 'app.bundle.js');
fs.writeFileSync(dest, header + body);
console.log(`built app.bundle.js — ${fs.statSync(dest).size} bytes from ${FILES.length} files; hooks: ${[...reactHooks].join(', ') || 'none'}`);
